### ISSUE TITLE
 Implement Task Completion Feature

### ISSUE THREAD

**Issue by jinyoung-plus** [jinyoung-plus/todo_list_application-Jinyoung_Ko-CDOF5#2]
#### Description
Currently, the To-Do List App lacks the ability to mark tasks as completed. Users can add tasks but cannot visually check them off.

#### Objective
- Implement a feature that allows users to mark tasks as completed.
- Once a task is checked, visually indicate its completion (e.g., strike-through text, change in color, etc.).

This feature should update the task's status both in the UI and in the local storage. Contributors are invited to propose and discuss implementation details.

**Comment by Sunghyun09** [comment]
This is an interesting topic. May I work on improving the documentation?

**Comment by jinyoung-plus** [comment]
Absolutely, your help with the documentation would be greatly appreciated. Please go ahead!

**Comment by jinyoung-plus** [comment]
I'm satisfied with the result.
